### ISSUE TITLE
x86 support

### ISSUE THREAD

**Issue by Yosho549** [MechaDragonX/Bheithir#5]
I´m running x86 and i want to run DRP in my Snes9x, and the program not work, ¿You can put x86 support?
Thanks

**Comment by MechaDragonX** [comment]
Sorry for the latest response.

As of the [latest commit](https://github.com/MechaDragonX/Bheithir/commit/7b029d1319bb52da7bd69eb1abb5f78494784715), it seems to work fine:
![x86](https://i.imgur.com/55DogFO.png "x86")
