### ISSUE TITLE
Problem starting the application

### ISSUE THREAD

**Issue by Chocolateunu** [MechaDragonX/Bheithir#6]
Hi!
I have a problem with this application and it is that I cannot start it.
When I open the application, it throws me a black tab that disappears instantly, and then nothing happens.

**Comment by ghost** [comment]
I got the same issue so I ran it from CMD and got this error:
`A fatal error occurred. The required library hostfxr.dll could not be found.
If this is a self-contained application, that library should exist in [F:\Games\DOSBox\rp\].
If this is a framework-dependent application, install the runtime in the global location [C:\Program Files\dotnet] or use the DOTNET_ROOT environment variable to specify the runtime location or register the runtime location in [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x64\InstallLocation].

The .NET Core runtime can be found at:
  - https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=win10-x64`
This is probably the issue. @MechaDragonX should append this to the readme file in this repo.

**Comment by ghost** [comment]
Addition: it must be the following version: https://dotnet.microsoft.com/download/dotnet-core/thank-you/runtime-desktop-3.1.10-windows-x64-installer

**Comment by zJairO** [comment]
I solved it installing this version of dotnet
https://dotnet.microsoft.com/download/dotnet/3.1

**Comment by MechaDragonX** [comment]
All builds currently are framework dependent. In the future, builds will be provided that are not framework dependent, since I know how to do that for Windows. As this program only works on Windows, I think that is sufficient. lol

Sorry about the trouble.

**Comment by Crustys41** [comment]
> All builds currently are framework dependent. In the future, builds will be provided that are not framework dependent, since I know how to do that for Windows. As this program only works on Windows, I think that is sufficient. lol
> 
> Sorry about the trouble.

but im a windows user and i have the same issue.

**Comment by MechaDragonX** [comment]
At the time, I was trying to create independent builds, but that ended up falling through. Make sure you follow the instructions in the readme. The application is a dumb console program and might immediately close. That's an unfortunately reality of opening console programs directly from File Explorer.
